name: Fetch news (4x daily)

on:
  schedule:
    # Horarios en UTC (Bogotá = UTC-5): 04:05, 10:05, 16:05, 22:05 hora Bogotá
    - cron: '5 9,15,21,3 * * *'
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i fast-xml-parser@^4 --no-audit --no-fund

      - name: Run fetcher
        run: node scripts/fetch_news.mjs

      - name: Commit changes
        run: |
          git config user.name "e3v-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/*.json
          git diff --quiet --cached || git commit -m "chore(data): update news/alerts [skip ci]"
          git push
